<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Objectives</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Arithmetic" data-toc-modified-id="Arithmetic-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Arithmetic</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Indexing-Numpy-Arrays" data-toc-modified-id="Indexing-Numpy-Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Indexing Numpy Arrays</a></span><ul class="toc-item"><li><span><a href="#Simple-Indexing" data-toc-modified-id="Simple-Indexing-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Simple Indexing</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Indexing-multi-dimensional-arrays" data-toc-modified-id="Indexing-multi-dimensional-arrays-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Indexing multi-dimensional arrays</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.2.2"><span class="toc-item-num">3.2.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.2.3"><span class="toc-item-num">3.2.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Advanced-Indexing" data-toc-modified-id="Advanced-Indexing-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Advanced Indexing</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.3.3"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.3.4"><span class="toc-item-num">3.3.4&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.3.5"><span class="toc-item-num">3.3.5&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-3.3.6"><span class="toc-item-num">3.3.6&nbsp;&nbsp;</span>Question:</a></span></li></ul></li></ul></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Broadcasting</a></span><ul class="toc-item"><li><span><a href="#Equal-shape-arrays" data-toc-modified-id="Equal-shape-arrays-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Equal-shape arrays</a></span></li><li><span><a href="#Broadcasting-with-a-single-value" data-toc-modified-id="Broadcasting-with-a-single-value-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Broadcasting with a single value</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Broadcasting-comparison-operators" data-toc-modified-id="Broadcasting-comparison-operators-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Broadcasting comparison operators</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-4.3.1"><span class="toc-item-num">4.3.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.3.2"><span class="toc-item-num">4.3.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.3.3"><span class="toc-item-num">4.3.3&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.3.4"><span class="toc-item-num">4.3.4&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.3.5"><span class="toc-item-num">4.3.5&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.3.6"><span class="toc-item-num">4.3.6&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Question:" data-toc-modified-id="Question:-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Boolean-Indexing" data-toc-modified-id="Boolean-Indexing-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Boolean Indexing</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-5.0.1"><span class="toc-item-num">5.0.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-5.0.2"><span class="toc-item-num">5.0.2&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Boolean-Indexing-in-Multiple-Dimensions" data-toc-modified-id="Boolean-Indexing-in-Multiple-Dimensions-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Boolean Indexing <em>in Multiple Dimensions</em></a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-5.1.1"><span class="toc-item-num">5.1.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-5.1.2"><span class="toc-item-num">5.1.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-5.1.3"><span class="toc-item-num">5.1.3&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-5.1.4"><span class="toc-item-num">5.1.4&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Broadcasting-and-Boolean-Indexing" data-toc-modified-id="Broadcasting-and-Boolean-Indexing-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Broadcasting and Boolean Indexing</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-5.2.2"><span class="toc-item-num">5.2.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-5.2.3"><span class="toc-item-num">5.2.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li></ul></li><li><span><a href="#Creating-Numpy-Arrays" data-toc-modified-id="Creating-Numpy-Arrays-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Creating Numpy Arrays</a></span><ul class="toc-item"><li><span><a href="#np.zeros" data-toc-modified-id="np.zeros-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>np.zeros</a></span></li><li><span><a href="#np.ones" data-toc-modified-id="np.ones-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>np.ones</a></span></li><li><span><a href="#np.full" data-toc-modified-id="np.full-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>np.full</a></span></li><li><span><a href="#np.linspace" data-toc-modified-id="np.linspace-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>np.linspace</a></span></li><li><span><a href="#Graphing" data-toc-modified-id="Graphing-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Graphing</a></span></li><li><span><a href="#np.arange" data-toc-modified-id="np.arange-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>np.arange</a></span></li><li><span><a href="#np.random.uniform-and-np.random.normal" data-toc-modified-id="np.random.uniform-and-np.random.normal-6.7"><span class="toc-item-num">6.7&nbsp;&nbsp;</span>np.random.uniform and np.random.normal</a></span></li><li><span><a href="#Numpy-Array-Questions" data-toc-modified-id="Numpy-Array-Questions-6.8"><span class="toc-item-num">6.8&nbsp;&nbsp;</span>Numpy Array Questions</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-6.8.1"><span class="toc-item-num">6.8.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-6.8.2"><span class="toc-item-num">6.8.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-6.8.3"><span class="toc-item-num">6.8.3&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-6.8.4"><span class="toc-item-num">6.8.4&nbsp;&nbsp;</span>Question:</a></span></li></ul></li></ul></li><li><span><a href="#Constraints-on-Arrays" data-toc-modified-id="Constraints-on-Arrays-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Constraints on Arrays</a></span></li><li><span><a href="#Reshaping-Arrays" data-toc-modified-id="Reshaping-Arrays-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Reshaping Arrays</a></span><ul class="toc-item"><li><span><a href="#Question" data-toc-modified-id="Question-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question" data-toc-modified-id="Question-8.4"><span class="toc-item-num">8.4&nbsp;&nbsp;</span>Question</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-8.5"><span class="toc-item-num">8.5&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-8.6"><span class="toc-item-num">8.6&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-8.7"><span class="toc-item-num">8.7&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-8.8"><span class="toc-item-num">8.8&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-8.9"><span class="toc-item-num">8.9&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Reshaping-does-not-make-a-copy" data-toc-modified-id="Reshaping-does-not-make-a-copy-8.10"><span class="toc-item-num">8.10&nbsp;&nbsp;</span>Reshaping does not make a copy</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-8.11"><span class="toc-item-num">8.11&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Dimensions" data-toc-modified-id="Dimensions-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Dimensions</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-9.3"><span class="toc-item-num">9.3&nbsp;&nbsp;</span>Question:</a></span><ul class="toc-item"><li><span><a href="#TRICKY-NOTE:-THERE-CAN-BE-A-DIMENSION-WITH-A-VALUE-OF-1." data-toc-modified-id="TRICKY-NOTE:-THERE-CAN-BE-A-DIMENSION-WITH-A-VALUE-OF-1.-9.3.1"><span class="toc-item-num">9.3.1&nbsp;&nbsp;</span>TRICKY NOTE: THERE CAN BE A DIMENSION WITH A VALUE OF 1.</a></span></li></ul></li><li><span><a href="#Question:" data-toc-modified-id="Question:-9.4"><span class="toc-item-num">9.4&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-9.5"><span class="toc-item-num">9.5&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-9.6"><span class="toc-item-num">9.6&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Broadcasting-multi-dimensional-arrays" data-toc-modified-id="Broadcasting-multi-dimensional-arrays-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Broadcasting multi-dimensional arrays</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-10.1"><span class="toc-item-num">10.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-10.2"><span class="toc-item-num">10.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-10.3"><span class="toc-item-num">10.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Array-Methods" data-toc-modified-id="Array-Methods-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Array Methods</a></span><ul class="toc-item"><li><span><a href="#Mathematical-methods" data-toc-modified-id="Mathematical-methods-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>Mathematical methods</a></span></li><li><span><a href="#Sums-and-Averages" data-toc-modified-id="Sums-and-Averages-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>Sums and Averages</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-11.2.1"><span class="toc-item-num">11.2.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.2.2"><span class="toc-item-num">11.2.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.2.3"><span class="toc-item-num">11.2.3&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.2.4"><span class="toc-item-num">11.2.4&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Declaring-an-axis-in-your-method" data-toc-modified-id="Declaring-an-axis-in-your-method-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>Declaring an axis in your method</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-11.3.1"><span class="toc-item-num">11.3.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.3.2"><span class="toc-item-num">11.3.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#REVIEW-Question:" data-toc-modified-id="REVIEW-Question:-11.3.3"><span class="toc-item-num">11.3.3&nbsp;&nbsp;</span>REVIEW Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.3.4"><span class="toc-item-num">11.3.4&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.3.5"><span class="toc-item-num">11.3.5&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Maximums-and-minimums" data-toc-modified-id="Maximums-and-minimums-11.4"><span class="toc-item-num">11.4&nbsp;&nbsp;</span>Maximums and minimums</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-11.4.1"><span class="toc-item-num">11.4.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.4.2"><span class="toc-item-num">11.4.2&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.4.3"><span class="toc-item-num">11.4.3&nbsp;&nbsp;</span>Question:</a></span></li></ul></li><li><span><a href="#Argument-Maximums-and-Minimums" data-toc-modified-id="Argument-Maximums-and-Minimums-11.5"><span class="toc-item-num">11.5&nbsp;&nbsp;</span>Argument Maximums and Minimums</a></span><ul class="toc-item"><li><span><a href="#Question:" data-toc-modified-id="Question:-11.5.1"><span class="toc-item-num">11.5.1&nbsp;&nbsp;</span>Question:</a></span></li><li><span><a href="#Question:" data-toc-modified-id="Question:-11.5.2"><span class="toc-item-num">11.5.2&nbsp;&nbsp;</span>Question:</a></span></li></ul></li></ul></li></ul></div>

# Numpy
## Objectives
- Understand how numpy arrays are different from python lists.
- Create arrays in numpy of a given shape.
- Use broadcasting to combine arrays.
- Index into numpy arrays:
    - Basic indexing, with values and slices, and
    - Advanced indexing with integer arrays
    - Boolean indexing.
- Use some numpy methods to process arrays:
    - Mathematical functions.
    - Aggregations.
    - Aggregation across axes.

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'retina'
plt.style.use('fivethirtyeight')

# Numpy: Efficient Array Computation in Python

The basic the unit of numpy is the array. Use it. Know it. Love it.

You will be using arrays every day for the rest of forever. So finish this assignment. Please.

This takes a list and creates a new array object.

In [ ]:
np.array([1,2,3,4,5])

We like to save it like so

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

And you can do pretty much anything to a numpy array that you could do to a list:

In [ ]:
x[2]

In [ ]:
x[:5]

In [ ]:
x[1:8:2]

In [ ]:
x[0] = 100
x

But, under the hood, very different things are going on...

  - Numpy arrays can hold one and only one type of data.
  - Numpy arrays are **super efficient** both in terms of memory footprint **and** computational efficiency.
  - Numpy arrays have a size, and the size cannot be changed.
  - Numpy arrays have a **shape**, which allows them to be multi-dimensional (examples forthcoming).
  
We'll review all these features later.

First, lets mess with this array.

### Question:

> PLEASE, NEVER EVER EVER COPY-PASTE WHILE DOING THESE QUESTIONS. OR ITS WRITER WILL HAUNT YOU. (AKA you won't learn to code it from memory. And in three weeks you'll realize you don't know it. We've seen it time and time again. It's worth it.) Make a second window if you need to copy it verbatim.

Index array x that we created above so that it returns: `array([2,3,4,5])`


In [ ]:
# write here:



<p>(Please type SOME actual answer before checking the solution. Even if you have NO IDEA. Just guess. It's good for you.)<p/>


<details><summary>Solution
</summary>

```python
x[2:6]
```
</details>

### Question:
Index array x so that it returns:

```python 
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 100])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x[::-1]
```
</details>

### Question:
Index array x so that it returns:


```python 
array([9, 7, 5, 3, 1])
```

Then save it as y.

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x[::-2]

y = x[::-2]
```
</details>

## Arithmetic

Before I tell you how addition is different with numpy arrays than with lists, let's make some predictions about how it works. This is a good way to check what we know before we learn something. 

### Question:
Without coding, what is the output in each of the cases below?

```python
#lists
[1,2,3,4] + [5,6,7,8]


#numpy arrays
np.array([1,2,3,4]) + np.array([5,6,7,8])
```

In [ ]:
# write both answers here:



<p>(Again, please write out your guess BEFORE clicking this button)<p/>


<details><summary>Solution</summary>

```python
# [1,2,3,4] + [5,6,7,8]
[1,2,3,4,5,6,7,8]

# np.array([1,2,3,4]) + np.array([5,6,7,8])
np.array([6,8,10,12])
```
</details>

The way we say that is "Lists do not natively add element-wise". But these newfangled arrays do. This is because arrays are made for math. Lots of math. Big Math.

### Question:
Without coding, what is the output in each of the cases below?

```python
#lists
[1,2,3,4] - [5,6,7,8]

#numpy arrays
np.array([1,2,3,4]) - np.array([5,6,7,8])
```

In [ ]:
# write both answers here:



<details><summary>Solution</summary>

```python
# [1,2,3,4] - [5,6,7,8]
TypeError


# np.array([1,2,3,4]) - np.array([5,6,7,8])
array([-4, -4, -4, -4])
```
</details>

### Question:
Without coding, what is the output in each of the cases below?

```python
#lists
[1,2,3,4] * [5,6,7,8]

# numpy arrays
np.array([1,2,3,4]) * np.array([5,6,7,8])
```

In [ ]:
# write both answers here:



<details><summary>Solution</summary>

```python
# [1,2,3,4] * [5,6,7,8]
TypeError


# np.array([1,2,3,4]) * np.array([5,6,7,8])
np.array([ 5, 12, 21, 32])
```
</details>

### Question:
Without coding, what is the output in each of the cases below?

```python
#lists
[1,2,3,4] / [5,6,7,8]

#numpy arrays
np.array([1,2,3,4]) / np.array([5,6,7,8])
```

In [ ]:
# write both answers here:


<details><summary>Solution</summary>

```python
# [1,2,3,4] / [5,6,7,8]
TypeError


# np.array([1,2,3,4]) / np.array([5,6,7,8])
array([0.2 , 0.3, 0.4ish, 0.5])
```
</details>

## Indexing Numpy Arrays

Arrays can take nested lists and make them into a pretty rectangle.

In [ ]:
np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])

In [ ]:
np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

Notice how the number of rows correlate to 'the # of lists' and number of columns are the '# of items per list.'

This is a nice convention because we can keep the (row, column) convention from linear algebra. Keeping this straight is paramount.

In [ ]:
x_list = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15], [16, 17, 18, 19]]
x_array = np.array(x_list)
x_array

In [ ]:
x_list[2][2]

In [ ]:
x_array[2][2]

In [ ]:
# But we can also use

In [ ]:
x_array[2, 2]

This is how we will be storing and working with most of our data. All three months. And beyond.

### Simple Indexing
#### Question:
How many rows will this array have? How many columns?

```python 
np.array([[10, 11], [14, 15], [18, 19]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
array([[10, 11],
       [14, 15],
       [18, 19]])

3 rows
2 columns
```
</details>

#### Question:
How many rows will this array have? How many columns?

```python 
np.array([[3, 4, 5]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
array([[3, 4, 5]])

1 rows
3 columns
```
</details>

#### Question:
How many rows will this array have? How many columns?

```python 
np.array([[3], [4], [5]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
array([[3],
       [4],
       [5]])

3 rows
1 columns

```
</details>

### Indexing multi-dimensional arrays

The usual list style indexing extends to multi-dimensional arrays:

In [ ]:
# Get first two rows.
x_array[:2, :]

In [ ]:
# Get first two columns.
x_array[:, :2]

In [ ]:
# Get first two rows and first two columns
x_array[:2, :2]

In [ ]:
# Get even numbered rows and columns
x_array[::2, ::2]

You can combine this with assignment to surgically alter arrays:

In [ ]:
x_array[:2, :2] = np.mean(x_array)
x_array

In [ ]:
# lets turn the array back to what it was
# lets turn it back for the questions
x_array[:2, :2] = ([0, 1], [4, 5])
x_array

#### Question:
Index x_array to return:

```python 
array([[10, 11],
       [14, 15],
       [18, 19]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array[2:,2:]
```
or 
```python
x_array[-3:,-2:]
```
</details>

#### Question:
Index x_array to return: 

```python 
array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])
```
(Try to *think* about if these are rows or columns. Before just guessing. How would you select them if they were lists? *Hint: Row,column)

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array[2:4]
```
</details>

#### Question:
Index x_array to return:


```python 
array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array[:, 2:4]
```
</details>

### Advanced Indexing

You can index an array with **another array** (or a list), and this is often referred to as **advanced indexing** or **fancy indexing**.

In [ ]:
x_items = np.array(['1st item', '2nd item', '3rd item', '4th item', '5th item'])
x_items

In [ ]:
index_array = np.array([0, 0, 4, 4, 2])
x_items[index_array]

Here's another example:

In [ ]:
colors = np.array(['red', 'blue'])
idx = np.array([0, 0, 1, 1, 0, 0, 1, 1])
colors[idx]

Here's yet another example:

In [ ]:
x_years = np.array([1901, 1950, 2010, 2021, 2030])
x_years

In [ ]:
index_array = np.array([0, 0, 4, 4, 2, 2])
x_years[index_array]

Advanced indexing also works for multi-dimensional arrays, but the results can be confusing.

In [ ]:
x_square = np.arange(20).reshape((5, 4))
x_square

In [ ]:
x_square[[0, 1, 2, 3], [0, 1, 2, 3]]

In [ ]:
#Pause - why did we get the answer above?

Again, you can use advanced indexing with assignment to change arrays:

In [ ]:
x_square[[0, 1, 2, 3], [0, 1, 2, 3]] = 999
x_square

Array indices can be combined with slices; for detailed information read https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html. But this is really pretty advanced material.

#### Question:
Use advanced indexing on q_square (defined in the cell below) to return: 


```python 
array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44]])
```

In [ ]:
q_square = np.arange(45).reshape(9,5)
q_square


In [ ]:
# write here:



<details><summary>Solution</summary>

```python
q_square[[1,3,8]]
```
or 
```python
q_square[[1,3,8], :]
```

</details>

#### Question:
Use advanced indexing on q_square to return:  

```python 
array([[ 1,  3,  4],
       [ 6,  8,  9],
       [11, 13, 14],
       [16, 18, 19],
       [21, 23, 24],
       [26, 28, 29],
       [31, 33, 34],
       [36, 38, 39],
       [41, 43, 44]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
q_square[:,[1,3,4]]
```
</details>

#### Question:
Use advanced indexing on q_square to return: 

```python 
array([[ 5, 25, 35],
       [ 6, 26, 36],
       [ 9, 29, 39]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
q_square[[1,5,7],[[0],[1],[4]]]
```
or 
```python
q_square[[[1,5,7],[1,5,7],[1,5,7]],[[0,0,0],[1,1,1],[2,2,2]]]
```
</details>

#### Question:
Using *x_array* and advanced indexing, return: 

```python 
array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array[:3,[1,3]]
```
</details>

#### Question:
Using x_array and advanced indexing return: 

```python 
array([[ 1,  3,  3],
       [ 5,  7,  7],
       [ 9, 11, 11]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array[:3,[1, 3, 3]]
```
</details>

#### Question:
Use advanced indexing and your own idx with *colors3* to return:

```python 
array(['red', 'green', 'green', 'blue', 'red', 'green'])
```

In [ ]:
colors3 = np.array(['red', 'blue', 'green'])

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
colors3[np.array([0,2,2,1,0,2])]
```
</details>

## Broadcasting

### Equal-shape arrays

Most of the standard binary operators in python can be used on arrays. These are interpreted as being applied **element by element**, so the result is an array of the same shape as the operands.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([2, 4, 6, 8, 10, 12])

In [ ]:
x + y

In [ ]:
x - y

In [ ]:
x * y

In [ ]:
y / x

In [ ]:
y % x

If one of the operands is a list, numpy will first convert it into an array.

In [ ]:
np.array([1, 2, 3]) + [1, 2, 3]

### Broadcasting with a single value

When the arrays are of different shape, they first have to be **broadcast** into arrays of the same shape. This feature is powerful but somewhat confusing.

The simplest example of broadcasting is when one array is a single element, or just a single value. In this case the value is converted into an array of the same shape as the other, but filled with that value. In effect, that value is combined with every element of the other array.

In [ ]:
2 * x

In [ ]:
y / 2

In [ ]:
x % 2

#### Question:
Using *x_array*, '100', and broadcasting return: 

```python 
array([  0, 100, 200, 300])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array[0] * 100
```
</details>

#### Question:
Using *x_array*, '100', and broadcasting return: 

```python 
array([   0,  400,  800, 1200, 1600])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array[:, 0] * 100
```
</details>

#### Question:
Sum the first and last rows of x_array. You will get:

```python 
array([16, 18, 20, 22])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array[0] + x_array[4]
```
</details>

### Broadcasting comparison operators

You can also broadcast with comparison operators, this is **very useful** when combined with something we'll talk about after this.

In [ ]:
x <= 3

In [ ]:
y / 2 == x

If you need to combine boolean arrays with logical operators, broadcasting also applys to the `&` and `|` operators (and and or):

In [ ]:
(x <= 2) | (x >= 5)

In [ ]:
(x >= 2) & (x <= 5)

Note the parentheses are necessary because of python's precedence rules.

#### Question:
using *x_array*, return true for each element that was less than 15 

```python 
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array < 15
```
</details>

#### Question:
For each element in the last column of *x_array*, return true if that element is less than 15 and false if it is not. You should get:
using *x_array*, return true for each element in the last column that was less than 15, and false if not.

```python 
array([ True,  True,  True, False, False])
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
x_array[:, -1] < 15
```
or 
```python
x_array[:, 3] < 15
```
</details>

#### Question:
Using *x_array*, return the remainder if you divided by 5:

```python 
array([[0, 1, 2, 3],
       [4, 0, 1, 2],
       [3, 4, 0, 1],
       [2, 3, 4, 0],
       [1, 2, 3, 4]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array % 5

```
</details>

#### Question:
Using *x_array*, return true if the remainder is 4 after dividing by 5.


```python
array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array % 5 == 4
```
</details>

#### Question:
Using *x_array*, return true if an element is evenly divisible by 2 and 3 (i.e. the remainder for each division is zero). 


```python 
array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False]])
```

In [ ]:
# write here: 

<details><summary>Solution</summary>

```python
(x_array % 2 == 0) & (x_array % 3 == 0)
```
</details>

#### Question:
Using *x_array*, return true if an element in column 3 is evenly divisible by 3 OR 7. You should get:

```python 
array([ True,  True, False,  True, False])

```
>(PLEASE don't copy/paste. Try to do it from memory!)


### Question:
Using `x_array`, find the numbers evenly divisible by 3 or 7 in column 3. 

>(PLEASE don't copy/paste. Try to do it from memory!)

```python 
array([ True,  True, False,  True, False])

```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
(x_array[:,3]%3==0) | (x_array[:,3]%7==0)
```
</details>

## Boolean Indexing

If you have an array of booleans (i.e. `True`'s and `False`'s), you can use these as indices too.  
But you'll get a new array containing only those elements that line up with a `True` in your index array.

Every row or column with a false will just go away, resulting in a array of a new size.

In [ ]:
x = np.arange(5)
x

In [ ]:
x[[True, True, False, False, True]]

#### Question:
Using *x* and boolean indexing return 

```python 
array([1, 2, 4])
```

In [ ]:
# write here: 


<details><summary>Solution</summary>

```python
x[[False, True, True, False, True]]
```
</details>

#### Question:
Using *sentence_array* and boolean indexing return 

```python 
array(["Hi,", "I'm", "getting", "better", "at", "numpy"])
```

In [ ]:
sentence_array = np.array(["Hi,", "I'm", "getting", "SQUIRREL", "better", "at", "AMALGAMATION","numpy"])

In [ ]:
# write here: 


<details><summary>Solution</summary>

```python
sentence_array[[True, True, True, False, True, True, False, True]]
```
</details>

### Boolean Indexing *in Multiple Dimensions*

You can use boolean indexing to select specific rows or columns in a multi-dimensional array:

In [ ]:
x = np.arange(20).reshape((5, 4))
x

In [ ]:
x[[True, False, True, True, False], :]

In [ ]:
x[:, [False, True, False, True]]

And, of course, this allows for some surgical operations:

In [ ]:
x[[True, False, True, True, False], :] = 999
x

When combined with broadcasting, this can get you to some neat places.

In [ ]:
x = np.random.randint(0, 10, size=(6, 10))
x

For example, we can return only the columns for which the value in the first row is bigger than five:

In [ ]:
x[:, x[0, :] > 5]

Return only the rows where the value in the first column is bigger than five:

In [ ]:
x[x[:, 0] > 5, :]

#### Question:
Using *x_array* and boolean indexing return 

```python 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [16, 17, 18, 19]])
```

In [ ]:
# write here: 


<details><summary>Solution</summary>

```python
x_array[[True,True, False, False, True]]
```
</details>

#### Question:
using *sentence_array* and boolean indexing return 

```python 
array([['I', 'will', 'write'],
       ['my', 'answer', 'before'],
       ['checking', 'the', 'solution']], dtype='<U8')
```

In [ ]:
promise_array = np.array([["I", "will", "HELP", "write"], ["my", "answer", "ME","before"], ["checking","the", "PLEASE","solution"]])
promise_array

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
promise_array[:,[True, True,False, True]]
```
</details>

#### Question:
Using *x_array* and boolean indexing return 

```python 
array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19]])
```

In [ ]:
# write here:



<details><summary>Solution</summary>

```python
x_array[:,[True,False, False, True]]
```
</details>

#### Question:
Using *x_array* return true if the number is greater than 5

```python 
array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array>5
```
</details>

### Broadcasting and Boolean Indexing

It is **very** useful to combine boolean indexing with broadcasting to create boolean index arrays. (Which we just did!)

In [ ]:
x % 2 == 0

In [ ]:
# Subset to the even entries.
x[x % 2 == 0]

#### Question:
using *x_array* and boolean indexing return 

```python 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [16, 17, 18, 19]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array[[True,True, False, False, True]]
```
</details>

#### Question:
Using *x_array*, '%', and '==' return all columns with a even first entry

```python 
array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array[:, x_array[0]%2 == 0 ]
```
</details>

#### Question:
Using *x_array*, inequalities, broadcasting, and boolean indexing return the rows who's third column is evenly divisible by 3 or 7. (Again, type from memory! It's good for you!)


```python 
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array[(x_array[:,3]%3==0) | (x_array[:,3]%7==0)]
```
</details>

## Creating Numpy Arrays

### np.zeros

`np.zeros` creates a new array of a given size, and fills it with zeros.

In [ ]:
np.zeros(10)

You can also create a **multi-dimensional** array by passing a tuple as the shape:

In [ ]:
np.zeros((5, 3))

### np.ones

This is just like `np.zeros`, but it fills the array with ones.

In [ ]:
x_ones = np.ones(10)
x_ones

### np.full

If you want another constant in your array, use `np.full`.

In [ ]:
np.full(shape=(3, 4), fill_value=np.pi)

In [ ]:
np.full((3, 4), np.pi)

### np.linspace

`np.linspace` creates an equally spaced grid of numbers between two endpoints. This comes in handy when generating data for graphs. 

In [ ]:
np.linspace(0, 1, num=11)

In [ ]:
np.linspace(0, 10, num=11)

In [ ]:
np.linspace(0, 1, num=21)

### Graphing

Combining functions, linspace, and broadcasting will help us make some cool graphs later. 

In [ ]:
def squared(x):
    return x**2

x_axis_values = np.linspace(-5,5,100)

fig, ax = plt.subplots()
ax.scatter(x=x_axis_values,y = squared(x_axis_values))

### np.arange

`np.arange` is just like the built-in python function `range`, but it makes an array.

In [ ]:
np.arange(10)

In [ ]:
np.arange(2, 10)

In [ ]:
np.arange(0, 10, 2)

**Fill in the blank:** The 2 in the above code `np.arange(0, 10, 2)` is referred to as the ____ parameter. 

<details><summary>Solution</summary>
This is called the step parameter. It's how large of a "step" you take between numbers generated in the array.
</details>

The differences between `np.linspace` and `np.arange` are

 * the third parameter of `linspace` is the number of points; for `arange` it's the step size, and
 * the endpoint is included with `linspace` but not with `arange` (e.g., np.arange(10) returns numbers up to 9).

### np.random.uniform and np.random.normal

The `np.random` subpackage contains some functions for creating arrays of random numbers.  These two are the most useful, but there are more!

In [ ]:
np.random.uniform(low=0.0, high=10.0, size=10).round(2)

In [ ]:
unif = np.random.uniform(low=0.0, high=10.0, size=10**7)

fig, ax = plt.subplots(figsize=(10, 6))
_ = ax.hist(unif, bins=100, color='crimson', alpha=0.8)

Does the above chart look like you'd expect it to?

In [ ]:
np.random.normal(loc=0.0, scale=1.0, size=10)#.round(2)

In [ ]:
unif = np.random.normal(loc=0.0, scale=1.0, size=10**7)

fig, ax = plt.subplots(figsize=(10, 6))
_ = ax.hist(unif, bins=100, color='crimson', alpha=0.8)

### Numpy Array Questions

#### Question:
Return an array of 10 random values between 0 and 5. Use shift+tab to see which parameters are which. 

```python 
array([4.96150642, 0.92838199, 4.94908329, 3.0829649 , 4.20193468,
       3.47927002, 1.97000483, 1.46018287, 3.25614441, 0.64609845])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
np.random.uniform(0,5,size=10)
```
</details>

#### Question:
Using linspace, return:

```python 
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
np.linspace(0,1,11)
```
</details>

#### Question:
Using logspace, return:  

```python 
array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
np.logspace(0, 5, 6)
```
</details>

#### Question:
Return 5 numbers with a mean of 10, who's average distance from 10 is about 1. (**Ahem** use the normal distribution.)

```python 
array([10.08397441, 10.5717336 , 11.50609933,  9.75519246,  9.42481597])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
np.random.normal(10,1,5)
```
</details>

## Constraints on Arrays

One other major difference between arrays and lists is that arrays **cannot be extended** (that means appended to or made bigger in any way).

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# x.append(10) <-- THIS WILL NOT WORK

Numpy arrays have a fixed **size**, which cannot be changed. **The size is the number of elements in the array.**

In [ ]:
x.size

So as a consequence, if you want to create a numpy array to hold some data, you **need to know how large your array needs to be at the time the array is created**.

## Reshaping Arrays

Although the total size of an array **cannot** be changed, the **shape** of the array can be changed, **as long as this change of shape does not create or destroy elements** (i.e., as long as the reshaping does not change the **size** of the array).

In [ ]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

In [ ]:
x.shape

In [ ]:
x.reshape((5, 2))

In [ ]:
x.reshape((2, 5))

If you do not know how many rows or columns to pick, you may use -1 to allow numpy to pick for you!

In [ ]:
# give me two rows, any number of columns
x.reshape((2, -1))

In [ ]:
# give me two columns, any number of rows
x.reshape((-1, 2))

Notice two things here:  
1. the product of the shape elements will *always* equal the size.
2. the 'shape' is (# of rows, # of columns). In that order. Make sure you think hard about this, as it will make your life less hellish later.

### Question

```python
    np.array([1,2,3])
```

has what shape?

In [ ]:
# write here



<details><summary>Solution</summary>

```python
(3,)
```
</details>

### Question

```python
    np.array([1,2,3])
```

has what size?

In [ ]:
# write here



<details><summary>Solution</summary>

```python
3
```
</details>

### Question

```python
    array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
```

has what shape?

In [ ]:
# write here



<details><summary>Solution</summary>

```python
(2, 10)
```
</details>

### Question

```python
    array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
```

has what size?

In [ ]:
# write here



<details><summary>Solution</summary>

```python
20
```
</details>

### Question:
Reshape x_array to have 2 rows and 10 columns. You should get:

```python 
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array.reshape(2,10)
```
</details>

### Question:
Reshape x_array to have 4 rows and 5 columns. You should get:

```python 
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array.reshape(4,5)
```
or 
```python
x_array.reshape(4,-1)
```
or 
```python
x_array.reshape(-1,5)
```
</details>

### Question:
Reshape x_array into a one dimensional array:

```python 
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array.reshape(-1)
```
or
```python
x_array.reshape(20)
```
</details>

### Question:

Reshape x_array into: 

```python 
array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])
```

<details><summary>Hint</summary>
How many rows and how many columns are there?
</details>

<details><summary>Hint 2 </summary>
Can you reshape x into those rows and columns?
</details>

<details><summary>Solution</summary>

```python
x_array.reshape(-1,1)
```
or
```python
x_array.reshape(20,1)
```
</details>

### Question:
If you know the shape of an array is (9,5) what is the size?

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
45
# because an array is like a cookie sheet, and the size is the number of cookies
# (which is a definition of a product)
```
</details>

### Reshaping does not make a copy

NOTE: Reshaping is very efficient, but it does **not** make a copy of the array!

In [ ]:
x = np.arange(10)
y = x.reshape((2, 5))
y

In [ ]:
y[1, 0] = 999
y

In [ ]:
x

(that 999 in x should shock you)

To make a copy of an array, use the `copy` method:

In [ ]:
x = np.arange(10)
y = x.reshape(2,5).copy()
y[1,0] = 999
y

In [ ]:
x

There, now x is unchanged

### Question:
After reshaping q_square into a 3x15 array, change element [2,8] to -5. What was the replaced element's previous value? Which index location was that in the original q_square?

In [ ]:
# write here



<details><summary>Solution</summary>

```python
q_square.reshape(3,15)[2,8]=-5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, -5, 39],
       [40, 41, 42, 43, 44]])
```
the value was 37

element (7,3) is changed in original q_square
</details>

## Dimensions

It's VERY worth noting that: 
* Arrays can have 1,2,3 or more **dimensions**. 
* The number of integers in the shape is the # of the dimensions.It's VERY worth noting that. Arrays can have 1,2,3 or more **dimensions**. The number of integers in the shape is the # of the dimensions.

shape = (2,2,2) has 3 dimensions

In [ ]:
np.arange(27).reshape((3,3,3))

You can think of this as a cube, or a series of cookie sheets.

The shape is always ```(sheet, row, column)```.

You can have more, but it gets harder to visualize.

This is a row of cubes:

In [ ]:
np.arange(36).reshape((3,3,2,2))

The shape is ```(cube, sheet, row, column)```. Take the time to see it in your head.

### Question:
What is the shape of this array?
```python
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>
(3,2,5)
    
```python
np.arange(30).reshape(3,2,5)
```
</details>

### Question:
Reshape x_array to print 5 sheets of 2x2 matrices.

```python
array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array.reshape(5,2,2)
```
</details>

### Question:
What is the shape of this array?
```python
array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
# (2,2,2,2)

#proof: np.arange(16).reshape(2,2,2,2)
```
</details>

#### TRICKY NOTE: THERE CAN BE A DIMENSION WITH A VALUE OF 1.

It's just hard to see.

In [ ]:
one_dim = x.reshape(10)
one_dim

In [ ]:
two_dims = x.reshape((1, 10))
two_dims

THESE ARE NOT QUITE THE SAME. Make sure you can see the difference. (it looks like __[[this]]__ )

In the first case, there are no rows/columns, just a single dimensioned list. In the second case, there is one row and many columns, but we only have one row to pick from. 

It's much easier to see if we have only one column instead.

### Question:
What is the shape of these two different arrays?
```python
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

array([[[ 0,  1,  2,  3]],
       [[ 4,  5,  6,  7]],
       [[ 8,  9, 10, 11]],
       [[12, 13, 14, 15]],
       [[16, 17, 18, 19]]])
```

In [4]:
# write here: 

<details><summary>Solution</summary>
(5,4) and (5,1,4)
    
```python
# proof
x_array.reshape(5,4)

x_array.reshape(5,1,4)
```
</details>

### Question:
Reshape x_array to print 2 sheets of 10 row 1 column matrices. 
```python
array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
x_array.reshape(2,10,1)
```
</details>

### Question:
Reshape x_array to print 4 layers of 5 column 1 row  matrices. 

```python 
array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19]]])
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
x_array.reshape(4,1,5)
```
</details>

## Broadcasting multi-dimensional arrays

Broadcasting also works for multi-dimensional arrays, but it takes some practice. As above, many copies are made of an array along one or more axes that previously had a length of one.

Let's see how this works.

In [ ]:
x = np.ones((5, 4))
x

The scalar case is the same as it ever was:

In [ ]:
x * 2

But now things get pretty interesting.  If you broadcast with a one dimensional array, cool stuff happens:

In [ ]:
b = np.array([1, 2, 3, 4])
x * b

Note that `b` must have the correct shape for this to happen.

In [ ]:
print("Shape of x:", x.shape)
print("Shape of b:   ", b.shape)

Arrays do not need to have the same number of dimensions to be broadcast together. To see if two arrays can be broadcast into the same shape, first line up the shapes of the arrays on the **right side** (as above).

>Broadcasting is possible if, for the dimensions being compared, either
>
> * both arrays have the same length(size),
> * one array has a length of 1 (in that dimension), or
> * that dimension does not exist in one of the arrays.

If a dimension has length 1, the resulting array takes the size of the other array for that dimension.

> For example, arrays A and B can be broadcast together:

Array | | | | |
---|---|---|---|--|
A      (4d array):  | 8 | 1 | 6 | 1 |  
B      (3d array):  |   | 7 | 1 | 5 |
Result (4d array):  | 8 | 7 | 6 | 5 |

To broadcast a single column across different rows we need to do some gymnastics.

In [ ]:
b = np.array([1, 2, 3, 4, 5])
# x * b

x * b doesn't work because the right-hand values (4 and 5) don't line up:

In [ ]:
print("Shape of x:", x.shape)
print("Shape of b:   ", b.shape)

To get this to work, we need to reshape `b`.

In [ ]:
b_reshaped = b.reshape((5, 1))
b_reshaped

Now the first dimensions are the same, and the second dimension of b is 1.

In [ ]:
print("Shape of x         :", x.shape)
print("Shape of b_reshaped:", b_reshaped.shape)

In case the two arrays have the same number of dimensions, as long as all the dimensions **either** match, or one of them is **exactly one**, the arrays will broadcast.

In [ ]:
x * b_reshaped

The unit length dimensions are **stretched** until the arrays have the same shape, then they are broadcast.

Let's do that again:

In [ ]:
b4 = np.array([1, 2, 3, 4])
b4_reshaped = b4.reshape((1, 4))

Note how all non-unit dimensions match:

In [ ]:
print("Shape of x          :", x.shape)
print("Shape of b4_reshaped:", b4_reshaped.shape)

So we can broadcast:

In [ ]:
x * b_reshaped

Cool beans.

We can even broadcast extraction from an array with indices. 
(If the arrays (or lists) used as indices don't have the same shape they will be broadcast together.)

In [ ]:
x_square

In [ ]:
x_square[[[0],[3]],[0,1,2]]

In [ ]:
x_square[[1,2,3], [[0],[3]]]

### Question:

Write out the output. (without running it!)

```python 
j_row = np.array([[1, 2, 3]])
j_col = np.array([[1],
                  [2],
                  [3]])
j_row + j_col
```

In [ ]:
# write here:


<p>(Please type SOME actual answer before checking the solution. Even if you have NO IDEA. Just guess. It's good for you.)<p/>


<details><summary>Solution
</summary>

```python
j=np.array([1,2,3])
j_row = j.reshape(1,-1)
j_col = j.reshape(-1,1)

j_row + j_col

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])
```
</details>

### Question:

Write out the output. (without running it!)

```python 
j = np.array([1, 2, 3])
j_col = np.array([[1],
                  [2],
                  [3]])
j + j_col
```

In [ ]:
# write here:


<p>(Please type SOME actual answer before checking the solution. Even if you have NO IDEA. Just guess. It's good for you.)<p/>


<details><summary>Solution
</summary>

```python
j=np.array([1,2,3])
j_col = j.reshape(-1,1)

j + j_col

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])
```
</details>

### Question:

Write out the output. (without running it!)

```python 
j = np.array([1, 2, 3])
j_col = np.array([[1],
                  [2],
                  [3]])
j_col + j_col
```

In [ ]:
# write here:


<p>(Please type SOME actual answer before checking the solution. Even if you have NO IDEA. Just guess. It's good for you.)<p/>


<details><summary>Solution
</summary>

```python
j_col + j_col

array([[2],
       [4],
       [6]])
```
</details>

## Array Methods

Arrays have many, many useful methods, and some of then have an argument called `axis` that increases their utility by allowing you to apply a method row-wise or column-wise (more on that later).
### Mathematical methods
Most of the day-to-day mathematical functions have representatives in numpy.

In [ ]:
x = np.linspace(1, 10, 5)
x

In [ ]:
np.exp(x)

In [ ]:
np.log(x)

In [ ]:
np.sin(2 * np.pi * x)

In [ ]:
np.cos(2 * np.pi * x)

In [ ]:
np.sqrt(x)

### Sums and Averages

It's easy and efficient to take the sum or average (arithmetic mean) of an array:

In [ ]:
x = np.arange(10)
x

In [ ]:
np.sum(x)

In [ ]:
np.mean(x)

When dealing with a multi-dimensional array, the default behaviour is to consume the entire thing:

In [ ]:
x = np.arange(20).reshape((4, 5))
x

In [ ]:
np.sum(x)

#### Question:
Using *x_array*, return the sum of its elements. You should get:


```python 
190
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.sum(x_array)
```
</details>

#### Question:
Using *x_array*, return the mean of its elements. You should get:

```python 
9.5
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.mean(x_array)
```
</details>

#### Question:
Using *x_array*, return the tangent of each value.

```python 
array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01, 8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00,
        -8.55993401e-01],
       [ 3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01]])
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.tan(x_array)
```
</details>

#### Question:
Return the sum of the squares of sine and cosine for each element in `x_array`.

```python 
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.sin(x_array)**2 + np.cos(x_array)**2
```
</details>

### Declaring an axis in your method

But what if we wanted the sum across a row?

You can also do **row sums** and **column sums** by supplying an axis argument.

In [ ]:
x = np.arange(6).reshape((2, 3))
x

In [ ]:
np.sum(x, axis=0)

In [ ]:
np.sum(x, axis=1)

These sums worked across different axes. One across the row, the other across the column. It's easy to lose track of which axis is being 'acted across'. The best way to keep it straight is *you will collapse whichever dimension is the axis you declare*.

For example, x.shape shows two dimensions:

In [ ]:
x.shape

If we want to add the elements together across-ways [(0+1+2), (3+4+5)], we are effectively smushing the columns together. No more columns.
So, remembering *(row, column)*, we will declare to remove the 2nd axis. So axis=1. (yes, 1 is the second axis)

In [ ]:
np.sum(x, axis=1).shape

We removed the 2nd axis, leaving 2 columns. Only they aren't columns anymore, persay. Because there is only one dimension left. One dimension with a value of 2.

In [ ]:
np.sum(x, axis=1)

If you want to keep the shape of the result, set parameter 'keepdims' to true. It literally leaves the dimension with a value of 1.

In [ ]:
np.sum(x, axis=0, keepdims=True).shape

It can be easier to visualize 'what just happened' as well.

In [ ]:
np.sum(x, axis=1, keepdims=True)

We summed 'acrossways'

#### Question:
Will this statement sum up-and-down-ways? (0+4+8+12+16) 
or across-ways? (0+1+2+3)

```python 
np.sum(x_array, axis=0)
```

__*(Think about which dimension is removed before just trying it)*__

In [ ]:
# write here: 




<details><summary>Solution</summary>

Up-and-down-ways, (0+4+8+12+16)

```python
array([40, 45, 50, 55])
```
</details>

#### Question:
Take the mean across-ways in x_array, the output should have one dimension. 

This is the result:

```python 
array([ 1.5,  5.5,  9.5, 13.5, 17.5])
```

__*(Think about which dimension is removed before just trying it)*__

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.mean(x_array, axis=1)
```

to see it better:

```python
np.mean(x_array, axis=1, keepdims=True)
array([[ 1.5],
       [ 5.5],
       [ 9.5],
       [13.5],
       [17.5]])
```
</details>

#### REVIEW Question:
Use np.arange to make an array that has 3 'sheets', 2 rows and 4 columns.

```python 
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.arange(4*3*2).reshape(3,2,4)
```
</details>

#### Question:

Sum the 'sheets' of the array you made in the previous question.

```python 
array([[24, 27, 30, 33],
       [36, 39, 42, 45]])
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
np.sum(np.arange(4*3*2).reshape(3,2,4), axis=0)
```
</details>

#### Question:

Add the 'rows' together of the array you made in the previous question. Keep the dimensions of the original array so we can see what's happening.

```python 
array([[[ 6],
        [22]],

       [[38],
        [54]],

       [[70],
        [86]]])
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
np.sum(np.arange(4*3*2).reshape(3,2,4), axis=2, keepdims=True)
```
</details>

### Maximums and minimums

Maximums and minimums work pretty much the same way as sums and averages.

In [ ]:
x = np.random.randint(0, 100, size=10)
x

In [ ]:
np.max(x)

In [ ]:
np.min(x)

The behavior for multi-dimensional arrays is the same as before:

In [ ]:
x = np.random.randint(0, 100, size=20).reshape((4, 5))
x

In [ ]:
# Column maximums
np.max(x, axis=0)

In [ ]:
# Row minimums
np.max(x, axis=1)

#### Question:
Find the highest number in each row for x_array:

```python 
array([ 3,  7, 11, 15, 19])
```

In [ ]:
# write here: 


<details><summary>Solution</summary>

```python
np.max(x_array, axis=1)

#or
x_array.max(axis=1)
```
</details>

#### Question:
Return the row maximum for each sheet of this array:
arange 24 items long, reshaped into a 2 sheet, 4 row, 3 column array.

__*Think about which dimension is removed before just trying it*__


```python 
array([[ 2,  5,  8, 11],
       [14, 17, 20, 23]])
```

In [ ]:
# write here: 


<details><summary>Solution</summary>

```python
np.max(np.arange(24).reshape(2,4,3), axis=2)

```
    
    or
    
```python
np.arange(24).reshape(2,4,3).max(axis=2)

```
</details>

#### Question:

Return the maximum value in each sheet of this array:
arange 24 items long, reshaped into a 2 sheet, 4 row, 3 column array.

```python
array([11, 23])
```

<details><summary>Solution</summary>

```python
np.max(np.max(np.arange(24).reshape(2,4,3), axis=1), axis=1)

#or 
np.arange(24).reshape(2,4,3).max(axis=1).max(axis=1)

```
</details>

### Argument Maximums and Minimums

Sometimes you don't need to know the maximum (or minimum), but **where the maximum occurs**.  This operation is called **argument maximum**.

In [ ]:
x

In [ ]:
np.argmax(x, axis=0)

In [ ]:
np.argmin(x, axis=1)

This can be very useful.  For example, if we want to find the maximum of a graph and then plot where it occurs:

In [ ]:
f = lambda x: x**4 + 2*x**3 - 12*x**2 - 2*x + 6
x = np.linspace(-5, 4, num=250)

fig, ax = plt.subplots()
ax.plot(x, f(x))
ax.set_ylim(-100, 100)

Now lets calculate the minimum and argmin and highlight it:

In [ ]:
mn, xmn = np.min(f(x)), x[np.argmin(f(x))] 

fig, ax = plt.subplots()
ax.plot(x, f(x))
ax.scatter(xmn, mn, s=100)
ax.set_ylim(-100, 100)

#### Question:
Find the minmum argument in q_square after its been reshaped to a 1 dimensional array. 
(q_square should still have the -5 term)


```python 
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, -5, 39],
       [40, 41, 42, 43, 44]])
min_term = 38
```

In [ ]:
# write here: 




<details><summary>Solution</summary>

```python
q_square.reshape(-1).argmin()

#or
q_square.argmin()
```
</details>

#### Question:
Find the minmum argument in `q_square` on each row. 
(`q_square` should still have the -5 term)


```python 
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, -5, 39],
       [40, 41, 42, 43, 44]])
min_term = 38
```

In [ ]:
# write here: 



<details><summary>Solution</summary>

```python
q_square.argmin(axis=1)
```
</details>